language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sezgi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sezgi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-297925301784"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  